export const GOOGLE_MAPS_API_KEY =
  process.env.EXPO_PUBLIC_GOOGLE_PLACES_API_KEY ||
  process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY ||
  "";

export const HAS_GOOGLE_MAPS_API_KEY =
  GOOGLE_MAPS_API_KEY.trim().length > 0 &&
  GOOGLE_MAPS_API_KEY !== "YOUR_GOOGLE_MAPS_API_KEY";

