export const FeaturedSpaces = [
  {
    id: "1",
    imageSource: require("@/assets/images/featuredSpaceImage1.png"),
    title: "2 Bedroom in-site apartment",
    location: "10 Onukem Str, Eneka, Port Harcourt",
    price: "N1,350,000",
    badgeType: "verified",
    duration: "annum",
  },
  {
    id: "2",
    imageSource: require("@/assets/images/featuredSpaceImage1.png"),
    title: "Atraz Palace Event Hall",
    location: "GRA Phase II, Port Harcourt",
    price: "N400,000",
    badgeType: "hot",
    duration: "day",
  },
  {
    id: "3",
    imageSource: require("@/assets/images/featuredSpaceImage1.png"),
    title: "Standard Self-contain Room",
    location: "Paradice Estate Elimbgu, Port Harcourt",
    price: "N300,000",
    badgeType: "diplace",
    duration: "annum",
  },
];
export const SpacesNearby = [
  {
    id: "1",
    imageSource: require("@/assets/images/SpacesNearbyImage1.png"),
    title: "2 Bedroom in-site apartment",
    location: "10 Onukem Str, Eneka, Port Harcourt",
    price: "N1,350,000",
    duration: "annum",
  },
  {
    id: "2",
    imageSource: require("@/assets/images/SpacesNearbyImage1.png"),
    title: "Atraz Palace Event Hall",
    location: "GRA Phase II, Port Harcourt",
    price: "N400,000",
    badgeType: "hot",
    duration: "day",
  },
  {
    id: "3",
    imageSource: require("@/assets/images/SpacesNearbyImage1.png"),
    title: "Standard Self-contain Room",
    location: "Paradice Estate Elimbgu, Port Harcourt",
    price: "N300,000",
    duration: "annum",
  },
];
