import { NotificationItem } from "@/types";

export const MockNotificationList: NotificationItem[] = [
  {
    public_id: "notif-1",
    user_id: "user-1",
    title: "Payment successful",
    message: "Your payment of ₦1,004,800 was completed successfully.",
    notification_type: "payment",
    priority: "high",
    action_url: "/views/inspection/payment-receipt",
    is_read: false,
    is_expired: false,
    is_scheduled: false,
    date_created: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
    date_modified: new Date().toISOString(),
    data: {
      amount: "1,004,800",
      currency: "₦",
      action_text: "Download receipt",
      action_type: "download_receipt",
    },
  },
  {
    public_id: "notif-2",
    user_id: "user-1",
    title: "Inspection scheduled",
    message: "Your inspection is confirmed for Wed. 9th August, 2025 within 10AM - 12PM.",
    notification_type: "inspection",
    priority: "medium",
    action_url: "/views/activities/todayActivity",
    is_read: false,
    is_expired: false,
    is_scheduled: false,
    date_created: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    date_modified: new Date().toISOString(),
    data: {
      action_text: "View schedule",
      action_type: "view_schedule",
    },
  },
  {
    public_id: "notif-3",
    user_id: "user-1",
    title: "Reminder",
    message: "Complete your booking within 10 minutes to secure your space.",
    notification_type: "booking",
    priority: "urgent",
    action_url: "/views/booking/booking-summary",
    is_read: true,
    is_expired: false,
    is_scheduled: false,
    date_created: "2025-07-30T10:00:00.000Z",
    date_modified: new Date().toISOString(),
    data: {
      action_text: "Complete booking",
      action_type: "complete_booking",
    },
  },
  {
    public_id: "notif-4",
    user_id: "user-1",
    title: "Listing Alert",
    message: "New apartment listing now available in Yaba.",
    notification_type: "property",
    priority: "low",
    action_url: "/(tabs)/discover",
    is_read: true,
    is_expired: false,
    is_scheduled: false,
    date_created: "2025-07-30T09:00:00.000Z",
    date_modified: new Date().toISOString(),
    data: {
      action_text: "View listing",
      action_type: "view_listing",
      location: "Yaba",
    },
  },
  {
    public_id: "notif-5",
    user_id: "user-1",
    title: "App Update",
    message: "A new version of Diplace is ready with improved performance and new features.",
    notification_type: "system",
    priority: "low",
    action_url: null,
    is_read: true,
    is_expired: false,
    is_scheduled: false,
    date_created: "2025-07-30T08:00:00.000Z",
    date_modified: new Date().toISOString(),
    data: {
      action_text: "View update",
      action_type: "view_update",
      version: "1.2.0",
    },
  },
];

export const Notes = [
  {
    id: "1",
    title: "Payment successful",
    date: "24 mins ago",
    desc: "Your payment of ₦1,004,800 was completed successfully.",
    type: "",
    action: "Download receipt",
    unread: true,
  },
  {
    id: "2",
    title: "Inspection scheduled",
    date: "Yesterday",
    desc: "Your inspection is confirmed for Wed. 9th August, 2025 within 10AM - 12PM.",
    type: "bell",
    action: "View schedule",
    unread: true,
  },
  {
    id: "3",
    title: "Reminder",
    date: "30 Jul, 2025",
    desc: "Complete your booking within 10 minutes to secure your space.",
    type: "bell",
    action: "Complete booking",
    unread: false,
  },
  {
    id: "4",
    title: "Listing Alert",
    date: "30 Jul, 2025",
    desc: "New apartment listing now available in Yaba.",
    type: "",
    action: "View listing",
    unread: false,
  },
  {
    id: "5",
    title: "App Update",
    date: "30 Jul, 2025",
    desc: "A new version of Diplace is ready with improved performance and new features.",
    type: "",
    action: "View update",
    unread: false,
  },
];

export const NotesTabs = [
  { id: "1", name: "All", icons: "" },
  { id: "2", name: "Unread", icons: "" },
  { id: "3", name: "Previous", icons: "" },
  {
    id: "4",
    name: "Dates",
    icons: require("@/assets/icons/calender-light.png"),
  },
];
