export const mockChats = [
    {
        id: "1",
        name: "Sahnay Kalu",
        message: "Personal read the run msg, tak run no...",
        time: "yesterday",
        avatar: "https://randomuser.me/api/portraits/men/1.jpg",
        unread: 1,
        isOnline: true,
        isVerified: true,
    },
    {
        id: "2",
        name: "Sahdatu Usman",
        message: "I have raised your concerns to the t...",
        time: "2 days ago",
        avatar: "https://randomuser.me/api/portraits/men/2.jpg",
        unread: 1,
        isOnline: false,
        isVerified: false,
    },
    {
        id: "3",
        name: "Torino Event Centre",
        message: "Please tell us more about the event...",
        time: "Wednesday",
        avatar: "https://randomuser.me/api/portraits/women/3.jpg",
        unread: 0,
        isOnline: false,
        isVerified: false,
    },
    {
        id: "4",
        name: "Atrice Palace",
        message: "We also offer interior lighting and chara...",
        time: "Tuesday",
        avatar: "https://randomuser.me/api/portraits/men/4.jpg",
        unread: 0,
        isOnline: true,
        isVerified: true,
    },
    {
        id: "5",
        name: "Chukka Waringpa",
        message: "Thanks! Gave cause waiting for you",
        time: "22.11",
        avatar: "https://randomuser.me/api/portraits/women/5.jpg",
        unread: 0,
        isOnline: false,
        isVerified: false,
    },
    {
        id: "6",
        name: "Insukuru Ziventin",
        message: "",
        time: "20.04",
        avatar: "https://randomuser.me/api/portraits/men/6.jpg",
        unread: 0,
        isOnline: false,
        isVerified: false,
    },
];